version: '3.0'
services:
  server:
    build:
      context: ./server
  meili:
    image: getmeili/meilisearch:v0.10.1
    ports:
    - "7700:7700"
  front:
    build:
      context: ./front
    ports:
    - "80:80"


